buildscript {
    dependencies {
        classpath platform(libs.dataservices.bom)
        classpath libs.logback.classic
        classpath libs.kernel.md.facade
    }
}

plugins {
    alias(libs.plugins.prepare.models)
}

prepareModels {
    inputDir = layout.projectDirectory.dir('src/test/resources')
    outputDir = layout.buildDirectory.dir('models')
}
