buildscript {
    apply from: rootProject.file('scripts/buildscript-platforms.gradle')

    dependencies {
        classpath a12Libs.kernel.tool.model.migration
        classpath libs.logback.classic
    }
}


plugins {
    id 'application'
    alias(gradlePluginLibs.plugins.shadow)
    alias(a12Plugins.plugins.prepare.models)
}

application {
    mainClass = 'com.mgmtp.a12.migration.Main'
}

// do not include shaded dependencies in the pom
configurations {
    shaded
    // but make them available for compilation/tests
    compileClasspath.extendsFrom(shaded)
    runtimeClasspath.extendsFrom(shaded)
    testCompileClasspath.extendsFrom(shaded)
    testRuntimeClasspath.extendsFrom(shaded)
}

prepareModels {
    inputDir = layout.projectDirectory.dir('src/test/resources')
    outputDir = layout.buildDirectory.dir('models')
}

dependencies {
    // A12 LIBRARIES
    shaded a12Libs.kernel.core.codegen.entities
    shaded a12Libs.kernel.core.parsetree.api
    shaded project(':form-model')
    shaded a12Libs.kernel.md.model
    shaded a12Libs.kernel.md.document.api
    shaded a12Libs.kernel.md.facade

    // THIRD PARTY LIBRARIES
    shaded libs.gson
    shaded libs.commons.cli
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    // TESTING
    testImplementation libs.testng
    testImplementation libs.hamcrest
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
}

// Shadow JAR configuration
shadowJar {
    archiveClassifier = 'cli-tool'
    configurations = [project.configurations.shaded]
    mergeServiceFiles()

    // Exclude signature files
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'

    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

tasks.named('assemble') {
    dependsOn(tasks.named('shadowJar'))
}

description = 'CLI tool that scans form models for inconsistencies between form model dependencies and document model computations'

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'Computation Relevancy Analyzer'
            }
        }
    }
}
