rootProject.name = 'form-engine'

dependencyResolutionManagement {
    versionCatalogs {
        if (file('gradle/a12-internal.versions.toml').exists()) {
            create('a12Internal') {
                from(files('gradle/a12-internal.versions.toml'))
            }
        }
    }
}

include(
    ":core",
    ":content-elements",
    ":content-elements-editor",
    ":codemod",
    ':devappServices',
    ':documentation',
    ':content-elements-devapp:resources:models',
    ':migrationTool',
    ':exampleModels',
    ':serialization-integration-test',
    ':form-parent',
    ':form-model',
    ':generator',
    ':modelGraph',
    ':java-codemod',
    ':preview'
)

['security', 'docker', 'performance-tests'].each { name ->
    if (file(name).exists()) {
        include(name)
    }
}

project(':devappServices').projectDir = file('devapp/resources/server/')
