////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License – EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

[#form-engine_rendering_data_roles]
= Data Roles

Following `data-role` values are set by the Form Engine to certain HTML elements rendered for the respective Form Model element:

[cols="1,1,1"]
|===
| Form Model element | HTML element | data-role

| Detached Repeat | outmost div | repeat-detached
| | table container div | repeat-content
| Embedded Repeat | outmost div | repeat-embedded
| | table container div | repeat-content
| Inline Repeat | outmost div | repeat-inline
| | table container div | repeat-content
| Screen | outmost div | screen
| Detached Repeat Detail Screen | outmost div | screen-detached-repeat-detail
| Button Panel | outmost div | button-panel
| Custom Cell | outmost div | custom-cell
| Custom Screen Element | outmost div | custom-screen-element
|===
