////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License – EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

[#form-engine_integration_non-redux]
= Non-Redux Applications

For any React application that has no Redux infrastructure, you can create and hold a private Redux store and configure it as usual. In order to interact with the outside React realm, you can pass respective parts of the configuration from outside.

== Example

The following code shows a minimal example to setup your own store and connect the engine components.

First you have to load your models:

[source,tsx]
----
include::assets/typescript/form-engine/minimal.tsx[tags=loadModels]
----

Then you need to unmarshall the Document Model and create a `IGeneratedCodeAccessor` with your validation code.

[source,tsx]
----
include::assets/typescript/form-engine/minimal.tsx[tags=unmarshallModel]
----

Furthermore, the Form Engine uses an in-memory representation of the Form Model, which extends the persistence Form Model by some information which are needed to render the form more efficient. Because of this you have to unmarshall the Form Model using the function `unmarshallFormModel`:

[source,tsx]
----
include::assets/typescript/form-engine/minimal.tsx[tags=unmarshallModel2]
----

After that you can create and initialize your store with your models:

[source,tsx]
----
include::assets/typescript/form-engine/minimal.tsx[tags=createStore]
----

At last you need to connect the components and render your engine

[source,tsx]
----
include::assets/typescript/form-engine/minimal.tsx[tags="connect,render"]
----

The whole code should then look like this:

[source,tsx]
----
include::assets/typescript/form-engine/minimal.tsx[tags="marker0,unmarshallModel,createStore,render,marker1,connect,loadModels"]
----
