////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License - EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

[#form-engine_tutorials_data_provider]
= Custom Form Data Provider

The Form Engine comes with a Client extension that provides two built-in data providers:

* the one resulting from calling the `createEmptyDocumentDataProvider` factory function. It can be used to create a new document when loading data in the "new instance" case.
* the `platformSingleDocumentDataProvider` which can be used for loading documents for existing instances and for saving or updating documents. It is meant to be used together with a Data Services backend.

But there are use cases, where those data providers are not sufficient and a custom solution is needed, e.g. when working with a custom backend.

The following code listing gives a detailed example for a custom data provider implementation.

[source,tsx]
----
include::assets/typescript/form-engine/tutorials/data-provider/customDataProvider.ts[tags=content]
----
