////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License – EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

[#form-engine_tutorials_behavior]
= Behavior Customization

There are different ways to customize the behavior of the engine. You can configure the `DispatchConfiguration` and add custom middlewares or reducers.
This part shows a small example for the first two options.

== Customizing DispatchConfiguration

Every UI-Event is handled by the `DispatchConfiguration`, which dispatches an event-action. You can overwrite parts of this configuration. It is mandatory to spread the `defaultMapDispatchToProps` into the map object. The following example will modify the default behavior for the `onNavigationButton` event. In this code the event-action `navigationButton` is always called with `validate = true` and `options = { validation: "full" }`, independent of the modelled button.

[source,tsx]
----
include::assets/typescript/form-engine/tutorials/customDispatchConfiguration.ts[tags=content]
----

== Custom Middleware

The following tutorial shows how a middleware for the event-action `eventButton` can be written and registered.

[source,tsx]
----
include::assets/typescript/form-engine/tutorials/event-button/onEventButtonClickedMiddleware.ts[tags=annotated-button]
----
