////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License - EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

= Breaking Change Management

The Form Engine library follows the general link:/docs/overall/breaking_change_management[A12 breaking change interpretation], but has the following exceptions:

- Adding new keys to the localization resource key objects is not considered a breaking change.
+
Otherwise, it would not be possible to provide overridable default translations for texts in components introduced with new optional features.
+
Compile errors resulting from this should point consumers to missing translations in locales without default translations.

- Adding new mandatory properties to the type DispatchConfiguration is not considered a breaking change, as it is expected that consumers customizing the dispatch configuration always spread the properties of the DispatchConfiguration returned by calling defaultMapDispatchToProps, which would include the new properties.

- Adding new mandatory properties to the types `FormModelMap`, `WidgetMap`, or `SelectorMap` is not considered a breaking change, as it is expected that consumers creating custom maps of these types always first spread the corresponding default map (`DefaultFormModelMap`, `DefaultWidgetMap`, or `DefaultSelectorMap`), which would include the new properties.

- The package `@com.mgmtp.a12.formengine/form-model-generator` is part of the A12 modeling tools and not supported for project use. It does not follow the A12 breaking change management policy.
