////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License – EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

= 2025.06-ext4

== Deprecation

=== Deep import paths of A12 Form Engine npm packages

Nested imports from the npm packages `@com.mgmtp.a12.formengine/formengine-core`, `@com.mgmtp.a12.formengine/formengine-content-elements` and `@com.mgmtp.a12.formengine/formengine-content-elements-editor` (e.g. `@com.mgmtp.a12.formengine/formengine-core/lib/models/index.js`)
are now deprecated in favor of top-level imports to avoid unnecessary breaking changes and reduce ongoing maintenance effort.

The ability to use the old-style ("long") imports will be removed in the next breaking release.

To migrate, first install or update the codemod with your preferred package manager, e.g. with `pnpm`:
[source,bash]
----
pnpm install -g @com.mgmtp.a12.formengine/formengine-codemod
----

Then run the specific recipe:
[source,bash]
----
formengine-codemod preferTopLevel <path to directory with tsconfig.json>

// or as a single command
pnpm dlx @com.mgmtp.a12.formengine/formengine-codemod preferTopLevel <path to directory with tsconfig.json>
----

For further details, run the codemod with the `--help` flag.
