////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial

Copyright (c) 2012-2026 mgm technology partners GmbH

Dual License
------------
This source file is part of the mgm A12 Platform and available under
a choice of two different licenses:

1. Open-Source License – EUPL v1.2
   You may redistribute and/or modify this file under the terms of the
   European Union Public License, version 1.2 - see https://eupl.eu/.

2. Commercial License
   Alternatively, you may obtain a commercial license from
   mgm technology partners GmbH, that permits use of this software
   under different terms (including support and maintenance services).

   Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
----------------------------------------------
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////

= 2025.06-ext2

== Breaking Changes

=== Content of Events.Attachments.UploadAttachmentsPayload changed

The content of the `UploadAttachmentsPayload` was changed at runtime. The property `formModelElementPath` incorrectly contained a model path to the Document Model element before. This has now been corrected, so that the payload contains a model path to the Form Model element from now on. For simple attachments this is the path to the attachment Control and for multi file upload Repeats this is the path to the Repeat.

If you are listening for this action and your code depends on the value of the `formModelElementPath` property, you need to adapt your code accordingly. The path to the Document Model element is still available in the action payload via the `files` property, where every file contains a document path to the attachment.

[source,tsx]
----
import { Action } from "typescript-fsa";

import { Events } from "@com.mgmtp.a12.formengine/formengine-core/lib/back-end/store/index.js";

function handleAction(action: Action<Events.Attachments.UploadAttachmentsPayload>) {
	// before
	const attachmentModelPath = action.payload.formModelElementPath;

	// after (please note, that this is a document path instead of a model path)
	const attachmentDocumentPath = action.payload.files.at(0)?.attachmentPath;

	// do something with the path
};
----

== Deprecation

=== Property formModelRepeatPath of the interface Events.Attachments.UploadAttachmentsPayload

The property `formModelRepeatPath` has been deprecated with Form Engine 38.1.0. This property is only used for multi file uploads. In this case it contains the same information as the property `formModelElementPath` and is therefore redundant.

The property can simply be removed from the payload.
