/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License - EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */

import { deepStrictEqual, ok, strictEqual } from "node:assert/strict";

import { query, within } from "@com.mgmtp.a12.devtools/react";
import type { LayoutGridProps } from "@com.mgmtp.a12.widgets/widgets-core";

import type { Models } from "../../../../back-end/store/index.js";
import { DefaultWidgetMap } from "../../../../view/index.js";
import { LAYOUT_GRID_COLUMN } from "../../../rtl-utils/data-roles.js";
import { mockFunctions } from "../../../rtl-utils/mock-map.js";
import type { RtlRenderWrapper } from "../../../rtl-utils/render-wrapper.js";
import { assertExists } from "../../../utils/assertions.js";
import type { Context } from "../../../utils/rtl-render-group.js";
import { RenderGroupFixture } from "../../../utils/rtl-render-group.js";
import { loadModels, setupFormEngineRendererWithRtlAsync } from "../../../utils/setup.js";
import { setupModelsFixture } from "../../../utils/setupFixture.js";
import { IDS as TitleIds } from "../../../utils/test-model-helpers/aria-level.js";
import { IDS } from "../../../utils/test-model-helpers/control-grid.js";
import {
	IDS as ExpressionLabelIds,
	expressionLabelDocument,
	formattedExpressionUiState
} from "../../../utils/test-model-helpers/expression-label.js";
import { IDS as ResponsiveIds } from "../../../utils/test-model-helpers/responsive-grid.js";

describe("api.view.layout", () => {
	describe("ControlGrid", () => {
		describe("hide when empty", () => {
			const models = setupModelsFixture("container", "container-visibility");

			it("statically empty", async () => {
				const wrapper = await setupFormEngineRendererWithRtlAsync({ models });
				const controlGrid = within(wrapper.baseElement).queryByText(
					"Control Grid should never be shown!"
				);
				ok(controlGrid === null);
			});

			const textToSearch = "Control Grid should not be shown if boolean field = true";
			it("dependent child visible", async () => {
				const wrapper = await setupFormEngineRendererWithRtlAsync({ models });
				const controlGrid = within(wrapper.baseElement).queryByText(textToSearch);
				ok(controlGrid);
			});

			it("dependent child hidden", async () => {
				const wrapper = await setupFormEngineRendererWithRtlAsync({
					models,
					data: { document: { rootGroup: { booleanField: true } } }
				});
				const controlGrid = within(wrapper.baseElement).queryByText(textToSearch);
				ok(controlGrid === null);
			});
		});

		interface RenderResult extends RtlRenderWrapper {
			colPropsById(id: string): LayoutGridProps.ColumnProps;
		}

		function RenderGroupFixtureForModels(models: Models): Context<RenderResult> {
			return RenderGroupFixture<RenderResult>(async () => {
				const wrapper = await setupFormEngineRendererWithRtlAsync({
					withWidgets: true,
					config: {
						widgetMap: mockFunctions(DefaultWidgetMap)
					},
					models
				});

				const colPropsById = (id: string) =>
					query(wrapper.widgetMap.LayoutGridColumn).withId(id).props();

				return {
					...wrapper,
					colPropsById
				};
			});
		}

		/**
		 * These tests render with widgets, because the tested size prop is set
		 * by widgets. Some cells are generated by widgets (those without HTML
		 * ids) - they are not tested.
		 */
		describe("layout", () => {
			const models = setupModelsFixture("container", "controlgrid");

			const { it, render } = RenderGroupFixtureForModels(models);

			describe("given a layout with three columns", () => {
				describe("and the controls which have no offset and span=1", () => {
					it("renders the layout correctly", () => {
						const column1 = render.wrapper.colPropsById("a12-stringField-field_55aca-group");
						const column2 = render.wrapper.colPropsById("a12-stringField-field_55aca-2-group");
						const column3 = render.wrapper.colPropsById("a12-stringField-field_55aca-3-group");

						deepStrictEqual(column1.size, { lg: 2, md: 2, sm: 2 }, "Wrong size in column 1");
						deepStrictEqual(column2.size, { lg: 4, md: 4, sm: 4 }, "Wrong size in column 2");
						deepStrictEqual(column3.size, { lg: 6, md: 6, sm: 6 }, "Wrong size in column 3");
					});
				});

				describe("and two controls where the first one has a span of 2", () => {
					it("renders the layout correctly", () => {
						// column1 and 3 are the spacer columns
						const column2 = render.wrapper.colPropsById("a12-stringField-field_55aca-4-group");
						const column4 = render.wrapper.colPropsById("a12-stringField-field_55aca-5-group");

						deepStrictEqual(column2.size, { lg: 6, md: 6, sm: 6 }, "Wrong size in column 2");
						deepStrictEqual(column4.size, { lg: 6, md: 6, sm: 6 }, "Wrong size in column 4");
					});
				});

				describe("and two controls where the first one has an offset of 1", () => {
					it("renders the layout correctly", () => {
						// column1 is the offset producing spacer column, 3 is a zero size spacer column
						const column2 = render.wrapper.colPropsById("a12-stringField-field_55aca-6-group");
						const column4 = render.wrapper.colPropsById("a12-stringField-field_55aca-7-group");

						deepStrictEqual(column2.size, { lg: 4, md: 4, sm: 4 }, "Wrong size in column 2");
						deepStrictEqual(column4.size, { lg: 6, md: 6, sm: 6 }, "Wrong size in column 4");
					});
				});

				describe("and two controls where the second one has an offset of 1", () => {
					it("renders the layout correctly", () => {
						// 1 and 3 are spacer columns
						const column2 = render.wrapper.colPropsById("a12-stringField-field_55aca-8-group");
						const column4 = render.wrapper.colPropsById("a12-stringField-field_55aca-9-group");

						deepStrictEqual(column2.size, { lg: 2, md: 2, sm: 2 }, "Wrong size in column 2");
						deepStrictEqual(column4.size, { lg: 6, md: 6, sm: 6 }, "Wrong size in column 4");
					});
				});

				describe("and one control with an offset of 2", () => {
					it("renders the layout correctly", () => {
						// 1 is a spacer columns
						const column2 = render.wrapper.colPropsById("a12-stringField-field_55aca-10-group");
						deepStrictEqual(column2.size, { lg: 6, md: 6, sm: 6 }, "Wrong size in column 2");
					});
				});
			});
		});

		describe("responsive layouts", () => {
			const models = setupModelsFixture("container.responsive-grid");
			const { it, render } = RenderGroupFixtureForModels(models);

			/**
			 * Returns a list of columns (their recorded props) but adds
			 * placeholders (undefined) for spacer columns.
			 *
			 * Explanation: Spacer columns are not rendered by us. widgets add
			 * them during rendering. They appear in the DOM but the rendering
			 * cannot be recorded by our mocks.
			 */
			function reconstructSpacerColumns(
				rowId: string
			): (LayoutGridProps.ColumnProps | undefined)[] {
				const row = within(render.wrapper.baseElement).getById(rowId);
				const cols = within(row).getAllByDataRole(LAYOUT_GRID_COLUMN);
				return cols.map(propsByCol);

				function propsByCol(col: HTMLElement) {
					return col.id
						? query(render.wrapper.widgetMap.LayoutGridColumn).withId(col.id).props()
						: undefined;
				}
			}

			describe("given a three-column responsive layout with lg 3-3-6, md 5-7-12 and sm 12-8-4", () => {
				function assertColumn(
					column: LayoutGridProps.ColumnProps | undefined,
					columnName: string,
					sizeClass: "lg" | "md" | "sm",
					sizeValue: number,
					spacerColumn = true,
					id?: string
				) {
					if (!spacerColumn) {
						assertExists(column, columnName + " is incorrect. Reason: unexpected spacerColumn.");
						strictEqual(
							column.size![sizeClass],
							sizeValue,
							columnName + " is incorrect. Reason: wrong size."
						);
						if (id) {
							strictEqual(column.id, id, columnName + " is incorrect. Reason: unexpected id.");
						}
					} else {
						ok(column === undefined, "Expected spacer column");
					}
				}

				describe("when available width is lg", () => {
					describe("when all controls have offset lg 0 and span lg 1", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_1);

							ok(columns.length === 6, "The row should have 3 cell columns and 3 spacer columns");

							assertColumn(columns.at(0), "spacerColumn1", "lg", 0);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"lg",
								3,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_1
							);
							assertColumn(columns.at(2), "spacerColumn2", "lg", 0);
							assertColumn(
								columns.at(3),
								"cellColumn2",
								"lg",
								3,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_2
							);
							assertColumn(columns.at(4), "spacerColumn3", "lg", 0);
							assertColumn(
								columns.at(5),
								"cellColumn3",
								"lg",
								6,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_3
							);
						});
					});
					describe("when one of the controls has offset lg > 0", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_2);

							ok(columns.length === 4, "The row should have 2 cell columns and 2 spacer columns");
							assertColumn(columns.at(0), "spacerColumn1", "lg", 3);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"lg",
								3,
								false,
								ResponsiveIds.GRID_ROW_2_CELL_1
							);
							assertColumn(columns.at(2), "spacerColumn2", "lg", 0);
							assertColumn(
								columns.at(3),
								"cellColumn2",
								"lg",
								6,
								false,
								ResponsiveIds.GRID_ROW_2_CELL_2
							);
						});
					});
					describe("when one of the controls has a span lg > 1", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_3);

							ok(columns.length === 2, "The row should have 1 cell column and 1 spacer column");
							assertColumn(columns.at(0), "spacerColumn", "lg", 0);
							assertColumn(
								columns.at(1),
								"cellColumn",
								"lg",
								12,
								false,
								ResponsiveIds.GRID_ROW_3_CELL_1
							);
						});
					});
				});

				describe("when available width is md", () => {
					describe("when all controls have offset md 0 and span md 1", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_1);

							ok(columns.length === 6, "The row should have 3 cell columns and 3 spacer columns");
							assertColumn(columns.at(0), "spacerColumn1", "md", 0);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"md",
								5,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_1
							);
							assertColumn(columns.at(2), "spacerColumn2", "md", 0);
							assertColumn(
								columns.at(3),
								"cellColumn2",
								"md",
								7,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_2
							);
							assertColumn(columns.at(4), "spacerColumn3", "md", 0);
							assertColumn(
								columns.at(5),
								"cellColumn3",
								"md",
								12,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_3
							);
						});
					});
					describe("when one of the controls has a span md > 1", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_2);

							ok(columns.length === 4, "The row should have 2 cell columns and 2 spacer columns");
							assertColumn(columns.at(0), "spacerColumn1", "md", 0);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"md",
								12,
								false,
								ResponsiveIds.GRID_ROW_2_CELL_1
							);
							assertColumn(columns.at(2), "spacerColumn2", "md", 0);
							assertColumn(
								columns.at(3),
								"cellColumn2",
								"md",
								12,
								false,
								ResponsiveIds.GRID_ROW_2_CELL_2
							);
						});
					});
					describe("when one of the controls has offset md > 0", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_3);

							ok(columns.length === 2, "The row should have 1 cell column and 1 spacer column");
							assertColumn(columns.at(0), "spacerColumn1", "md", 5);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"md",
								7,
								false,
								ResponsiveIds.GRID_ROW_3_CELL_1
							);
						});
					});
				});

				describe("when available width is sm", () => {
					describe("when all controls have offset sm 0 and span sm 1", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_1);

							ok(columns.length === 6, "The row should have 3 cell columns and 3 spacer columns");
							assertColumn(columns.at(0), "spacerColumn1", "sm", 0);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"sm",
								3,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_1
							);
							assertColumn(columns.at(2), "spacerColumn2", "sm", 0);
							assertColumn(
								columns.at(3),
								"cellColumn2",
								"sm",
								8,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_2
							);
							assertColumn(columns.at(4), "spacerColumn3", "sm", 0);
							assertColumn(
								columns.at(5),
								"cellColumn3",
								"sm",
								4,
								false,
								ResponsiveIds.GRID_ROW_1_CELL_3
							);
						});
					});
					describe("when one of the controls has a span sm > 1", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_2);

							ok(columns.length === 4, "The row should have 2 cell columns and 2 spacer columns");
							assertColumn(columns.at(0), "spacerColumn1", "sm", 0);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"sm",
								3,
								false,
								ResponsiveIds.GRID_ROW_2_CELL_1
							);
							assertColumn(columns.at(2), "spacerColumn2", "sm", 0);
							assertColumn(
								columns.at(3),
								"cellColumn2",
								"sm",
								12,
								false,
								ResponsiveIds.GRID_ROW_2_CELL_2
							);
						});
					});
					describe("when one of the controls has offset sm > 0", () => {
						it("renders the layout correctly", () => {
							const columns = reconstructSpacerColumns(ResponsiveIds.GRID_ROW_3);

							ok(columns.length === 2, "The row should have 1 cell column and 1 spacer column");
							assertColumn(columns.at(0), "spacerColumn1", "sm", 3);
							assertColumn(
								columns.at(1),
								"cellColumn1",
								"sm",
								8,
								false,
								ResponsiveIds.GRID_ROW_3_CELL_1
							);
						});
					});
				});
			});

			describe("fallback mechanism", () => {
				function assertColumn(
					column: LayoutGridProps.ColumnProps | undefined,
					columnName: string,
					sizeValue: object,
					spacerColumn = true,
					id?: string
				) {
					if (!spacerColumn) {
						assertExists(column, columnName + " is incorrect. Reason: unexpected spacerColumn.");
						deepStrictEqual(
							column.size,
							sizeValue,
							columnName + " is incorrect. Reason: wrong size."
						);
						if (id) {
							strictEqual(column.id, id, columnName + " is incorrect. Reason: unexpected id.");
						}
					} else {
						ok(column === undefined, "Expected spacer column");
					}
				}

				describe("given a responsive layout, where layout md is missing", () => {
					it("falls back to the values of layout lg for md", () => {
						const columns = reconstructSpacerColumns(ResponsiveIds.GRID_FALLBACK_MD_ROW);

						ok(columns.length === 8, "The row should have 4 cell columns and 4 spacer columns");
						assertColumn(columns.at(0), "spacerColumn1", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							columns.at(1),
							"cellColumn1",
							{ lg: 5, md: 5, sm: 6 },
							false,
							ResponsiveIds.GRID_FALLBACK_MD_CELL_1
						);
						assertColumn(columns.at(2), "spacerColumn2", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							columns.at(3),
							"cellColumn2",
							{ lg: 3, md: 3, sm: 6 },
							false,
							ResponsiveIds.GRID_FALLBACK_MD_CELL_2
						);
						assertColumn(columns.at(4), "spacerColumn3", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							columns.at(5),
							"cellColumn3",
							{ lg: 2, md: 2, sm: 3 },
							false,
							ResponsiveIds.GRID_FALLBACK_MD_CELL_3
						);
						assertColumn(columns.at(6), "spacerColumn4", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							columns.at(7),
							"cellColumn4",
							{ lg: 2, md: 2, sm: 9 },
							false,
							ResponsiveIds.GRID_FALLBACK_MD_CELL_4
						);
					});
				});

				describe("given a responsive layout, where layout sm is missing", () => {
					it("falls back to the values of layout md for sm", () => {
						const cols = reconstructSpacerColumns(ResponsiveIds.GRID_FALLBACK_SM_ROW);

						ok(cols.length === 6, "The row should have 3 cell columns and 3 spacer columns");
						assertColumn(cols.at(0), "spacerColumn1", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							cols.at(1),
							"cellColumn1",
							{ lg: 1, md: 8, sm: 8 },
							false,
							ResponsiveIds.GRID_FALLBACK_SM_CELL_1
						);
						assertColumn(cols.at(2), "spacerColumn2", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							cols.at(3),
							"cellColumn2",
							{ lg: 6, md: 4, sm: 4 },
							false,
							ResponsiveIds.GRID_FALLBACK_SM_CELL_2
						);
						assertColumn(cols.at(4), "spacerColumn3", { lg: 0, md: 0, sm: 0 });
						assertColumn(
							cols.at(5),
							"cellColumn3",
							{ lg: 5, md: 12, sm: 12 },
							false,
							ResponsiveIds.GRID_FALLBACK_SM_CELL_3
						);
					});
				});
			});
		});

		describe("props", () => {
			const models = setupModelsFixture("container", "controlgrid");

			function setup(screenName?: string) {
				return setupFormEngineRendererWithRtlAsync({
					models,
					ui: screenName
						? {
								screenLocation: [
									{
										locationPath: [{ elementName: screenName }],
										path: []
									}
								]
							}
						: undefined
				});
			}

			describe("verticalAlignment", () => {
				const { it, render } = RenderGroupFixture(() => setup("VerticalAlignment"));

				async function assertAlignment(
					controlGridId: string,
					alignment: "top" | "middle" | "bottom"
				): Promise<void> {
					const grid = query(render.wrapper.widgetMap.LayoutGrid).withId(controlGridId).props();
					strictEqual(grid.verticalAlignment, alignment);
				}

				describe("given a control-grid with verticalAlignment='TOP' set in the model", () => {
					it("sets the verticalAlignment prop to 'top'", () => {
						assertAlignment(IDS.topControlGrid, "top");
					});
				});

				describe("given a control-grid with verticalAlignment='MIDDLE' set in the model", () => {
					it("sets the verticalAlignment prop to 'middle'", () => {
						assertAlignment(IDS.middleControlGrid, "middle");
					});
				});

				describe("given a control-grid with verticalAlignment='BOTTOM' set in the model", () => {
					it("sets the verticalAlignment prop to 'bottom'", () => {
						assertAlignment(IDS.bottomControlGrid, "bottom");
					});
				});
			});
		});

		describe("title", () => {
			describe("label", () => {
				const { it, render } = RenderGroupFixtureForModels(loadModels("a11y", "aria-level"));
				describe("with a multilingual label defined in the model", () => {
					it("renders a title", () => {
						const headline = within(render.wrapper.baseElement).getByTestId(
							TitleIds.GRID_WITH_LABEL
						);
						strictEqual(headline.textContent, "control grid with label");
					});
				});

				describe("with no label defined in the model", () => {
					it("doesn't render a title", () => {
						const headline = within(render.wrapper.baseElement).queryByTestId(
							TitleIds.GRID_WITHOUT_LABEL
						);

						ok(headline === null);
					});
				});
			});

			describe("with an expression label defined in the model", () => {
				const expressionLabelModels = setupModelsFixture("localization", "expression-label");
				it("renders a title", async () => {
					const wrapper = await setupFormEngineRendererWithRtlAsync({
						models: expressionLabelModels,
						data: { document: expressionLabelDocument }
					});

					const headline = within(wrapper.baseElement).queryByTestId(
						ExpressionLabelIds.CONTROL_GRID
					);

					strictEqual(headline?.textContent, "Control Grid: TestValue");
				});

				it("renders a formatted title if the expression contained markdown formatting", async () => {
					const wrapper = await setupFormEngineRendererWithRtlAsync({
						models: expressionLabelModels,
						data: { document: expressionLabelDocument },
						ui: formattedExpressionUiState
					});

					const headline = within(wrapper.baseElement).queryByTestId(
						ExpressionLabelIds.CONTROL_GRID_FORMATTED
					);

					strictEqual(
						headline?.firstElementChild?.innerHTML,
						"ControlGrid in italics: <em>TestValue</em>"
					);
				});
			});
		});
	});
});
