buildscript {
    dependencies {
        classpath platform(libs.dataservices.bom)
        classpath libs.build.utilities
        classpath libs.dataservices.modelgraph
        classpath libs.kernel.md.facade
        classpath libs.logback.classic
    }
}

plugins {
    alias(libs.plugins.prepare.models)
}

prepareModels {
    generateValidationCodeInConverter = true
}

tasks.named('clean') {
    delete layout.buildDirectory
    delete layout.projectDirectory.dir('../../target')
}

tasks.register('generateModelGraph', JavaExec) {
    dependsOn(tasks.named('prepareModels'))

    final String dir = prepareModels.outputDir.asFile.get().toString()
    final String modelGraphFile = "${dir}/modelGraph.json"

    classpath = buildscript.configurations.classpath
    mainClass = 'com.mgmtp.a12.dataservices.modelgraph.fs.impl.ModelGraphGenerator'

    inputs.dir(prepareModels.outputDir)
    outputs.file(modelGraphFile)

    args("--output=${modelGraphFile}")

    // models are copied into one directory as the generator class can only handle a "single" input
    args(dir)
}

tasks.named('assemble') {
    dependsOn(tasks.named('generateModelGraph'))
}
